# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geodata_matching_dialog_base.ui'
#
# Created: Mon May 27 11:13:04 2019
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName(_fromUtf8("DockWidget"))
        DockWidget.resize(382, 811)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(150)
        sizePolicy.setHeightForWidth(DockWidget.sizePolicy().hasHeightForWidth())
        DockWidget.setSizePolicy(sizePolicy)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.btSuiv = QtGui.QPushButton(self.dockWidgetContents)
        self.btSuiv.setGeometry(QtCore.QRect(240, 170, 111, 23))
        self.btSuiv.setObjectName(_fromUtf8("btSuiv"))
        self.label = QtGui.QLabel(self.dockWidgetContents)
        self.label.setGeometry(QtCore.QRect(110, 140, 101, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.currentId = QtGui.QLineEdit(self.dockWidgetContents)
        self.currentId.setGeometry(QtCore.QRect(219, 140, 61, 21))
        self.currentId.setObjectName(_fromUtf8("currentId"))
        self.btGo = QtGui.QPushButton(self.dockWidgetContents)
        self.btGo.setGeometry(QtCore.QRect(280, 139, 75, 23))
        self.btGo.setObjectName(_fromUtf8("btGo"))
        self.tableCoordFeu = QtGui.QTableWidget(self.dockWidgetContents)
        self.tableCoordFeu.setGeometry(QtCore.QRect(22, 330, 341, 181))
        self.tableCoordFeu.setRowCount(5)
        self.tableCoordFeu.setColumnCount(2)
        self.tableCoordFeu.setObjectName(_fromUtf8("tableCoordFeu"))
        self.btSynchronize = QtGui.QPushButton(self.dockWidgetContents)
        self.btSynchronize.setGeometry(QtCore.QRect(22, 530, 221, 23))
        self.btSynchronize.setObjectName(_fromUtf8("btSynchronize"))
        self.fileImportGrille = QgsFileWidget(self.dockWidgetContents)
        self.fileImportGrille.setGeometry(QtCore.QRect(90, 100, 261, 27))
        self.fileImportGrille.setObjectName(_fromUtf8("fileImportGrille"))
        self.label_3 = QtGui.QLabel(self.dockWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 111, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.line_2 = QtGui.QFrame(self.dockWidgetContents)
        self.line_2.setGeometry(QtCore.QRect(90, 210, 281, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.btPrec = QtGui.QPushButton(self.dockWidgetContents)
        self.btPrec.setGeometry(QtCore.QRect(130, 170, 111, 23))
        self.btPrec.setObjectName(_fromUtf8("btPrec"))
        self.btZoomGrille = QtGui.QPushButton(self.dockWidgetContents)
        self.btZoomGrille.setGeometry(QtCore.QRect(30, 170, 101, 23))
        self.btZoomGrille.setObjectName(_fromUtf8("btZoomGrille"))
        self.fileOuvrirInventaireCSV = QgsFileWidget(self.dockWidgetContents)
        self.fileOuvrirInventaireCSV.setGeometry(QtCore.QRect(110, 230, 251, 27))
        self.fileOuvrirInventaireCSV.setObjectName(_fromUtf8("fileOuvrirInventaireCSV"))
        self.label_2 = QtGui.QLabel(self.dockWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(10, 240, 91, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.btViderFichier = QtGui.QPushButton(self.dockWidgetContents)
        self.btViderFichier.setGeometry(QtCore.QRect(243, 530, 111, 23))
        self.btViderFichier.setObjectName(_fromUtf8("btViderFichier"))
        self.btControler = QtGui.QPushButton(self.dockWidgetContents)
        self.btControler.setGeometry(QtCore.QRect(100, 7, 50, 50))
        self.btControler.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/PoussePousseEditData/img/controle.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btControler.setIcon(icon)
        self.btControler.setIconSize(QtCore.QSize(45, 45))
        self.btControler.setObjectName(_fromUtf8("btControler"))
        self.label_6 = QtGui.QLabel(self.dockWidgetContents)
        self.label_6.setGeometry(QtCore.QRect(22, 310, 151, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.line_3 = QtGui.QFrame(self.dockWidgetContents)
        self.line_3.setGeometry(QtCore.QRect(90, 80, 281, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.label_7 = QtGui.QLabel(self.dockWidgetContents)
        self.label_7.setGeometry(QtCore.QRect(30, 280, 91, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.fileControleCSV = QtGui.QLineEdit(self.dockWidgetContents)
        self.fileControleCSV.setEnabled(False)
        self.fileControleCSV.setGeometry(QtCore.QRect(110, 280, 251, 20))
        self.fileControleCSV.setObjectName(_fromUtf8("fileControleCSV"))
        self.btCheck = QtGui.QPushButton(self.dockWidgetContents)
        self.btCheck.setEnabled(False)
        self.btCheck.setGeometry(QtCore.QRect(150, 7, 50, 50))
        self.btCheck.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/PoussePousseEditData/img/valider.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btCheck.setIcon(icon1)
        self.btCheck.setIconSize(QtCore.QSize(40, 40))
        self.btCheck.setObjectName(_fromUtf8("btCheck"))
        self.btReload = QtGui.QPushButton(self.dockWidgetContents)
        self.btReload.setGeometry(QtCore.QRect(50, 7, 50, 50))
        self.btReload.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/PoussePousseEditData/img/reload.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btReload.setIcon(icon2)
        self.btReload.setIconSize(QtCore.QSize(40, 40))
        self.btReload.setObjectName(_fromUtf8("btReload"))
        self.btVider = QtGui.QPushButton(self.dockWidgetContents)
        self.btVider.setGeometry(QtCore.QRect(290, 7, 50, 50))
        self.btVider.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/PoussePousseEditData/img/vider.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btVider.setIcon(icon3)
        self.btVider.setIconSize(QtCore.QSize(35, 43))
        self.btVider.setObjectName(_fromUtf8("btVider"))
        self.label_8 = QtGui.QLabel(self.dockWidgetContents)
        self.label_8.setGeometry(QtCore.QRect(90, 633, 71, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.dockWidgetContents)
        self.label_9.setGeometry(QtCore.QRect(20, 652, 141, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.dockWidgetContents)
        self.label_10.setGeometry(QtCore.QRect(90, 670, 71, 20))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.dockWidgetContents)
        self.label_11.setGeometry(QtCore.QRect(30, 692, 151, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.dockWidgetContents)
        self.label_12.setGeometry(QtCore.QRect(120, 714, 46, 13))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.dockWidgetContents)
        self.label_13.setGeometry(QtCore.QRect(120, 734, 46, 13))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.txtCompletion = QtGui.QLineEdit(self.dockWidgetContents)
        self.txtCompletion.setGeometry(QtCore.QRect(160, 630, 201, 20))
        self.txtCompletion.setObjectName(_fromUtf8("txtCompletion"))
        self.txtMissing = QtGui.QLineEdit(self.dockWidgetContents)
        self.txtMissing.setGeometry(QtCore.QRect(160, 650, 201, 20))
        self.txtMissing.setObjectName(_fromUtf8("txtMissing"))
        self.txtError = QtGui.QLineEdit(self.dockWidgetContents)
        self.txtError.setGeometry(QtCore.QRect(160, 670, 201, 20))
        self.txtError.setObjectName(_fromUtf8("txtError"))
        self.txtRMSE = QtGui.QLineEdit(self.dockWidgetContents)
        self.txtRMSE.setGeometry(QtCore.QRect(160, 690, 201, 20))
        self.txtRMSE.setObjectName(_fromUtf8("txtRMSE"))
        self.txtSBN = QtGui.QLineEdit(self.dockWidgetContents)
        self.txtSBN.setGeometry(QtCore.QRect(160, 730, 201, 20))
        self.txtSBN.setObjectName(_fromUtf8("txtSBN"))
        self.txtSBE = QtGui.QLineEdit(self.dockWidgetContents)
        self.txtSBE.setGeometry(QtCore.QRect(160, 710, 201, 20))
        self.txtSBE.setObjectName(_fromUtf8("txtSBE"))
        self.line_4 = QtGui.QFrame(self.dockWidgetContents)
        self.line_4.setGeometry(QtCore.QRect(0, 570, 371, 16))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.label_14 = QtGui.QLabel(self.dockWidgetContents)
        self.label_14.setGeometry(QtCore.QRect(10, 80, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.dockWidgetContents)
        self.label_15.setGeometry(QtCore.QRect(12, 210, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.btNew = QtGui.QPushButton(self.dockWidgetContents)
        self.btNew.setGeometry(QtCore.QRect(240, 7, 50, 50))
        self.btNew.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/PoussePousseEditData/img/new.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btNew.setIcon(icon4)
        self.btNew.setIconSize(QtCore.QSize(35, 37))
        self.btNew.setObjectName(_fromUtf8("btNew"))
        self.fileValidationCSV = QtGui.QLineEdit(self.dockWidgetContents)
        self.fileValidationCSV.setEnabled(False)
        self.fileValidationCSV.setGeometry(QtCore.QRect(110, 590, 251, 20))
        self.fileValidationCSV.setObjectName(_fromUtf8("fileValidationCSV"))
        self.label_16 = QtGui.QLabel(self.dockWidgetContents)
        self.label_16.setGeometry(QtCore.QRect(27, 590, 81, 20))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        DockWidget.setWindowTitle(_translate("DockWidget", "PoussePousseEditData", None))
        self.btSuiv.setText(_translate("DockWidget", ">>", None))
        self.label.setText(_translate("DockWidget", "Cellule en cours :", None))
        self.btGo.setText(_translate("DockWidget", "Go", None))
        self.btSynchronize.setText(_translate("DockWidget", "Synchroniser le fichier et le layer", None))
        self.label_3.setText(_translate("DockWidget", "Fichier grille:", None))
        self.btPrec.setText(_translate("DockWidget", "<<", None))
        self.btZoomGrille.setText(_translate("DockWidget", "Zoom Grille", None))
        self.label_2.setText(_translate("DockWidget", "Fichier saisie CSV:", None))
        self.btViderFichier.setText(_translate("DockWidget", "Vider fichier", None))
        self.label_6.setText(_translate("DockWidget", "Vue sur le fichier en cours:", None))
        self.label_7.setText(_translate("DockWidget", "Contrôle CSV:", None))
        self.label_8.setText(_translate("DockWidget", "Completion:", None))
        self.label_9.setText(_translate("DockWidget", "Theoretical missing number:", None))
        self.label_10.setText(_translate("DockWidget", "Mean error: ", None))
        self.label_11.setText(_translate("DockWidget", "Root mean square error:", None))
        self.label_12.setText(_translate("DockWidget", "X bias:", None))
        self.label_13.setText(_translate("DockWidget", "Y bias:", None))
        self.label_14.setText(_translate("DockWidget", "GRILLE", None))
        self.label_15.setText(_translate("DockWidget", "POINT", None))
        self.label_16.setText(_translate("DockWidget", "Validation CSV:", None))

from qgis.gui import QgsFileWidget
