# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'poussepousse_editdata_dialog_base.ui'
#
# Created: Tue Jun 18 10:39:49 2019
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DockWidget(object):
    def setupUi(self, DockWidget):
        DockWidget.setObjectName(_fromUtf8("DockWidget"))
        DockWidget.resize(382, 811)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(150)
        sizePolicy.setHeightForWidth(DockWidget.sizePolicy().hasHeightForWidth())
        DockWidget.setSizePolicy(sizePolicy)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.btSuiv = QtGui.QPushButton(self.dockWidgetContents)
        self.btSuiv.setGeometry(QtCore.QRect(240, 170, 111, 23))
        self.btSuiv.setObjectName(_fromUtf8("btSuiv"))
        self.label = QtGui.QLabel(self.dockWidgetContents)
        self.label.setGeometry(QtCore.QRect(110, 140, 101, 20))
        self.label.setObjectName(_fromUtf8("label"))
        self.currentId = QtGui.QLineEdit(self.dockWidgetContents)
        self.currentId.setGeometry(QtCore.QRect(219, 140, 61, 21))
        self.currentId.setObjectName(_fromUtf8("currentId"))
        self.btGo = QtGui.QPushButton(self.dockWidgetContents)
        self.btGo.setGeometry(QtCore.QRect(280, 139, 75, 23))
        self.btGo.setObjectName(_fromUtf8("btGo"))
        self.tableCoordFeu = QtGui.QTableWidget(self.dockWidgetContents)
        self.tableCoordFeu.setGeometry(QtCore.QRect(12, 340, 241, 181))
        self.tableCoordFeu.setRowCount(5)
        self.tableCoordFeu.setColumnCount(2)
        self.tableCoordFeu.setObjectName(_fromUtf8("tableCoordFeu"))
        self.btSynchronize = QtGui.QPushButton(self.dockWidgetContents)
        self.btSynchronize.setGeometry(QtCore.QRect(270, 340, 101, 51))
        self.btSynchronize.setObjectName(_fromUtf8("btSynchronize"))
        self.fileImportGrille = QgsFileWidget(self.dockWidgetContents)
        self.fileImportGrille.setGeometry(QtCore.QRect(90, 100, 261, 27))
        self.fileImportGrille.setObjectName(_fromUtf8("fileImportGrille"))
        self.label_3 = QtGui.QLabel(self.dockWidgetContents)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 111, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.line_2 = QtGui.QFrame(self.dockWidgetContents)
        self.line_2.setGeometry(QtCore.QRect(0, 210, 371, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.btPrec = QtGui.QPushButton(self.dockWidgetContents)
        self.btPrec.setGeometry(QtCore.QRect(130, 170, 111, 23))
        self.btPrec.setObjectName(_fromUtf8("btPrec"))
        self.btZoomGrille = QtGui.QPushButton(self.dockWidgetContents)
        self.btZoomGrille.setGeometry(QtCore.QRect(30, 170, 101, 23))
        self.btZoomGrille.setObjectName(_fromUtf8("btZoomGrille"))
        self.fileOuvrirInventaireCSV = QgsFileWidget(self.dockWidgetContents)
        self.fileOuvrirInventaireCSV.setGeometry(QtCore.QRect(110, 230, 251, 27))
        self.fileOuvrirInventaireCSV.setObjectName(_fromUtf8("fileOuvrirInventaireCSV"))
        self.label_2 = QtGui.QLabel(self.dockWidgetContents)
        self.label_2.setGeometry(QtCore.QRect(10, 240, 91, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.btViderFichier = QtGui.QPushButton(self.dockWidgetContents)
        self.btViderFichier.setGeometry(QtCore.QRect(270, 400, 101, 23))
        self.btViderFichier.setObjectName(_fromUtf8("btViderFichier"))
        self.btControler = QtGui.QPushButton(self.dockWidgetContents)
        self.btControler.setGeometry(QtCore.QRect(160, 7, 50, 50))
        self.btControler.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/PoussePousseEditData/img/controle.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btControler.setIcon(icon)
        self.btControler.setIconSize(QtCore.QSize(45, 45))
        self.btControler.setObjectName(_fromUtf8("btControler"))
        self.label_6 = QtGui.QLabel(self.dockWidgetContents)
        self.label_6.setGeometry(QtCore.QRect(10, 320, 151, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Arial"))
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.line_3 = QtGui.QFrame(self.dockWidgetContents)
        self.line_3.setGeometry(QtCore.QRect(0, 70, 371, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.label_7 = QtGui.QLabel(self.dockWidgetContents)
        self.label_7.setGeometry(QtCore.QRect(30, 280, 91, 20))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.fileControleCSV = QtGui.QLineEdit(self.dockWidgetContents)
        self.fileControleCSV.setEnabled(False)
        self.fileControleCSV.setGeometry(QtCore.QRect(110, 280, 251, 20))
        self.fileControleCSV.setObjectName(_fromUtf8("fileControleCSV"))
        self.btCheck = QtGui.QPushButton(self.dockWidgetContents)
        self.btCheck.setEnabled(False)
        self.btCheck.setGeometry(QtCore.QRect(210, 7, 50, 50))
        self.btCheck.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/PoussePousseEditData/img/valider.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btCheck.setIcon(icon1)
        self.btCheck.setIconSize(QtCore.QSize(40, 40))
        self.btCheck.setObjectName(_fromUtf8("btCheck"))
        self.btReload = QtGui.QPushButton(self.dockWidgetContents)
        self.btReload.setGeometry(QtCore.QRect(110, 7, 50, 50))
        self.btReload.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/PoussePousseEditData/img/reload.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btReload.setIcon(icon2)
        self.btReload.setIconSize(QtCore.QSize(40, 40))
        self.btReload.setObjectName(_fromUtf8("btReload"))
        self.label_8 = QtGui.QLabel(self.dockWidgetContents)
        self.label_8.setGeometry(QtCore.QRect(90, 663, 71, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.dockWidgetContents)
        self.label_9.setGeometry(QtCore.QRect(20, 682, 141, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_10 = QtGui.QLabel(self.dockWidgetContents)
        self.label_10.setGeometry(QtCore.QRect(90, 700, 71, 20))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.dockWidgetContents)
        self.label_11.setGeometry(QtCore.QRect(30, 722, 151, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.dockWidgetContents)
        self.label_12.setGeometry(QtCore.QRect(120, 744, 46, 13))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_13 = QtGui.QLabel(self.dockWidgetContents)
        self.label_13.setGeometry(QtCore.QRect(120, 764, 46, 13))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.txtCompletion = QtGui.QLineEdit(self.dockWidgetContents)
        self.txtCompletion.setGeometry(QtCore.QRect(160, 660, 201, 20))
        self.txtCompletion.setObjectName(_fromUtf8("txtCompletion"))
        self.txtMissing = QtGui.QLineEdit(self.dockWidgetContents)
        self.txtMissing.setGeometry(QtCore.QRect(160, 680, 201, 20))
        self.txtMissing.setObjectName(_fromUtf8("txtMissing"))
        self.txtError = QtGui.QLineEdit(self.dockWidgetContents)
        self.txtError.setGeometry(QtCore.QRect(160, 700, 201, 20))
        self.txtError.setObjectName(_fromUtf8("txtError"))
        self.txtRMSE = QtGui.QLineEdit(self.dockWidgetContents)
        self.txtRMSE.setGeometry(QtCore.QRect(160, 720, 201, 20))
        self.txtRMSE.setObjectName(_fromUtf8("txtRMSE"))
        self.txtSBN = QtGui.QLineEdit(self.dockWidgetContents)
        self.txtSBN.setGeometry(QtCore.QRect(160, 760, 201, 20))
        self.txtSBN.setObjectName(_fromUtf8("txtSBN"))
        self.txtSBE = QtGui.QLineEdit(self.dockWidgetContents)
        self.txtSBE.setGeometry(QtCore.QRect(160, 740, 201, 20))
        self.txtSBE.setObjectName(_fromUtf8("txtSBE"))
        self.line_4 = QtGui.QFrame(self.dockWidgetContents)
        self.line_4.setGeometry(QtCore.QRect(0, 540, 371, 16))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.fileValidationCSV = QtGui.QLineEdit(self.dockWidgetContents)
        self.fileValidationCSV.setEnabled(False)
        self.fileValidationCSV.setGeometry(QtCore.QRect(110, 560, 251, 20))
        self.fileValidationCSV.setObjectName(_fromUtf8("fileValidationCSV"))
        self.label_16 = QtGui.QLabel(self.dockWidgetContents)
        self.label_16.setGeometry(QtCore.QRect(27, 560, 81, 20))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_4 = QtGui.QLabel(self.dockWidgetContents)
        self.label_4.setGeometry(QtCore.QRect(24, 590, 131, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.dockWidgetContents)
        self.label_5.setGeometry(QtCore.QRect(35, 610, 131, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_14 = QtGui.QLabel(self.dockWidgetContents)
        self.label_14.setGeometry(QtCore.QRect(41, 630, 111, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.txtNbCell = QtGui.QLineEdit(self.dockWidgetContents)
        self.txtNbCell.setGeometry(QtCore.QRect(160, 590, 111, 20))
        self.txtNbCell.setObjectName(_fromUtf8("txtNbCell"))
        self.txtNbAcquis = QtGui.QLineEdit(self.dockWidgetContents)
        self.txtNbAcquis.setGeometry(QtCore.QRect(160, 610, 111, 20))
        self.txtNbAcquis.setObjectName(_fromUtf8("txtNbAcquis"))
        self.txtNbValidation = QtGui.QLineEdit(self.dockWidgetContents)
        self.txtNbValidation.setGeometry(QtCore.QRect(160, 630, 111, 20))
        self.txtNbValidation.setObjectName(_fromUtf8("txtNbValidation"))
        DockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def retranslateUi(self, DockWidget):
        DockWidget.setWindowTitle(_translate("DockWidget", "PoussePousseEditData", None))
        self.btSuiv.setText(_translate("DockWidget", ">>", None))
        self.label.setText(_translate("DockWidget", "Cellule en cours :", None))
        self.btGo.setText(_translate("DockWidget", "Go", None))
        self.btSynchronize.setText(_translate("DockWidget", "Synchroniser \n"
" le fichier \n"
" et le layer", None))
        self.label_3.setText(_translate("DockWidget", "Fichier grille:", None))
        self.btPrec.setText(_translate("DockWidget", "<<", None))
        self.btZoomGrille.setText(_translate("DockWidget", "Zoom Grille", None))
        self.label_2.setText(_translate("DockWidget", "Fichier saisie CSV:", None))
        self.btViderFichier.setText(_translate("DockWidget", "! Vider fichier", None))
        self.btControler.setToolTip(_translate("DockWidget", "Saisir les points de contrôle", None))
        self.label_6.setText(_translate("DockWidget", "Vue sur le fichier en cours:", None))
        self.label_7.setText(_translate("DockWidget", "Contrôle CSV:", None))
        self.btCheck.setToolTip(_translate("DockWidget", "Valider", None))
        self.btReload.setToolTip(_translate("DockWidget", "Revenir à l\'acquisition", None))
        self.label_8.setText(_translate("DockWidget", "Completion:", None))
        self.label_9.setText(_translate("DockWidget", "Theoretical missing number:", None))
        self.label_10.setText(_translate("DockWidget", "Mean error: ", None))
        self.label_11.setText(_translate("DockWidget", "Root mean square error:", None))
        self.label_12.setText(_translate("DockWidget", "X bias:", None))
        self.label_13.setText(_translate("DockWidget", "Y bias:", None))
        self.label_16.setText(_translate("DockWidget", "Validation CSV:", None))
        self.label_4.setText(_translate("DockWidget", "Nombre de cellules tirées:", None))
        self.label_5.setText(_translate("DockWidget", "Acquisition sample size:", None))
        self.label_14.setText(_translate("DockWidget", "Validation sample size:", None))

from qgis.gui import QgsFileWidget
